version: '3'

services:

    pulsar:
        image: apachepulsar/pulsar
        expose:
            - 6650 
            - 8080
        command: >
            /bin/bash -c
            "bin/pulsar standalone &> /dev/null"

    pulsar-dashboard:
        image: apachepulsar/pulsar-dashboard
        depends_on:
            - pulsar
        ports:
            - "80:80"
        environment:
            - SERVICE_URL=http://pulsar:8080

    producer:
        build:
            context: .
            dockerfile: Dockerfile.producer
        depends_on:
            - pulsar

    consumer:
        build:
            context: .
            dockerfile: Dockerfile.consumer
        depends_on:
            - pulsar